#!/usr/bin/python3

import re
import sys
from typing import Dict

import requests

URL = "https://en.wikipedia.org/w/api.php"
TAG_RE = re.compile(r"<[^>]+>")
HTML_ESCAPE_TABLE = {
    "&amp;": "&",
    "&quot;": "'",
    "&apos;": "'",
    "&gt;": ">",
    "&lt;": "<",
    '"': "'",  # not an html escape but needed
}


def remove_tags(text: str) -> str:
    """
    Remove tags from a piece of html
    """
    for key, value in HTML_ESCAPE_TABLE.items():
        text = text.replace(key, value)

    return TAG_RE.sub("", text)


def format_url(parameters: Dict) -> str:
    """
    Format a url for the wikipedia api
    """

    def _format_parameter(key: str, value: str) -> str:
        return f"{key}={value}" if value is not None else f"{key}"

    return f"{URL}?{'&'.join(_format_parameter(key, value) for key, value in parameters.items())}"


def scrape(title: str) -> str:
    """
    Search for wikipedia articles matching a given query term
    """

    defaults = {
        "action": "parse",
        "formatversion": 1,
        "prop": "wikitext",
        "format": "json"
    }

    url = format_url({**defaults, **{"page": title}})
    response = requests.get(url)

    if response.status_code != 200:
        raise KeyError(f"Bad search: {title}")

    return response.text


if __name__ == "__main__":

    url = sys.argv[1]
    print(scrape(url))
